---
# These tasks install http and the php modules.

- name: Install http and php etc
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

- name: insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: http service state
  service: name=apache2 state=started enabled=yes


